$env:GROQ_API_KEY='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'
$env:CLOUDINARY_API_KEY='784879961441172'
$env:CLOUDINARY_API_SECRET='cVYiNw6X942Vse55_D6C9WpfuCU'
$env:CLOUDINARY_CLOUD_NAME='dcetkhi95'
$env:ENCRYPTION_KEY='M4rd1qu3@2026!!'
$env:PGDATABASE='railway'
$env:PGHOST='viaduct.proxy.rlwy.net'
$env:PGPASSWORD='IrPGAVgJwEtouuHzFzcZktbDiAxxFhEV'
$env:PGPORT='12484'
$env:PGUSER='postgres'
Start-Process -FilePath 'C:\Users\Mardique\.jdks\ms-21.0.12\bin\java.exe' -ArgumentList '-jar','target\MardiqueWeb-0.0.1-SNAPSHOT.jar' -WorkingDirectory 'C:\Users\Mardique\Downloads\MardiqueWeb'
